global:
  application_name: my_blog_app
  default_ec2_keyname: null
  default_platform: PHP 7.3
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application